[project]
name = 'Alien-Civilization-Contact-Protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.message-decryption]
path = 'contracts/message-decryption.clar'
clarity_version = 2
epoch = 2.5

[contracts.response-formulation]
path = 'contracts/response-formulation.clar'
clarity_version = 2
epoch = 2.5

[contracts.signal-detection]
path = 'contracts/signal-detection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
